cache:
  - Build\ThirdParty\vcpkg
  
image: Visual Studio 2017

install:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: BuildThirdPartyDependencies.bat

build:
  parallel: true
  project: CppCoverage.sln
