version: 1.0.{build}
image: Visual Studio 2017
environment:
  BOOST_ROOT: C:\Libraries\boost_1_67_0
install:
- cmd: vcpkg install poco:x86-windows-dbg
- cmd: vcpkg install protobuf:x86-windows-dbg
- cmd: vcpkg install gtest:x86-windows-dbg
- cmd: vcpkg install ctemplate:x86-windows-dbg
- cmd: vcpkg install range-v3:x86-windows-dbg
- cmd: vcpkg export poco:x86-windows-dbg protobuf:x86-windows-dbg gtest:x86-windows-dbg ctemplate:x86-windows-dbg range-range-v3:x86-windows-dbg --nuget --nuget-id=ThirdParty --nuget-version=1.2.0
- cmd: nuget install ThirdParty -Source C:\Tools\vcpkg -OutputDirectory packages
cache: C:\Tools\vcpkg\installed\
build:
  project: CppCoverage.sln
  parallel: true
  verbosity: normal
