version: 1.0.{build}
image: Visual Studio 2017
install:
- cmd: vcpkg install poco:x64-windows poco:x86-windows
- cmd: vcpkg install protobuf:x64-windows protobuf:x86-windows
- cmd: vcpkg install gtest:x64-windows gtest:x86-windows
- cmd: vcpkg install ctemplate:x64-windows ctemplate:x86-windows
- cmd: vcpkg install range-v3:x64-windows range-v3:x86-windows
- cmd: vcpkg integrate install
cache: c:\tools\vcpkg\installed\
build:
  project: CppCoverage.sln
  parallel: true
  verbosity: normal
