version: 1.0.{build}
image: Visual Studio 2017
install:
- cmd: BuildThirdPartyDependencies.bat
cache: Build\ThirdParty\vcpkg\installed
build:
  project: CppCoverage.sln
  parallel: true
  verbosity: normal
