version: 1.0.{build}
image: Visual Studio 2017
install:
- cmd: vcpkg install poco:x64-windows poco:x86-windows
- cmd: vcpkg install protobuf:x64-windows protobuf:x86-windows
- cmd: vcpkg install gtest:x64-windows gtest:x86-windows
- cmd: vcpkg install ctemplate:x64-windows ctemplate:x86-windows
- cmd: vcpkg install boost-optional:x64-windows boost-optional:x86-windows
- cmd: vcpkg install boost-filesystem:x64-windows boost-filesystem:x86-windows
- cmd: vcpkg install boost-algorithm:x64-windows boost-algorithm:x86-windows
- cmd: vcpkg install boost-container:x64-windows boost-container:x86-windows
- cmd: vcpkg install boost-program-options:x64-windows boost-program-options:x86-windows
- cmd: vcpkg install boost-regex:x64-windows boost-regex:x86-windows
- cmd: vcpkg install boost-range:x64-windows boost-range:x86-windows
- cmd: vcpkg install boost-log:x64-windows boost-log:x86-windows
- cmd: vcpkg install boost-property-tree:x64-windows boost-property-tree:x86-windows
- cmd: vcpkg install boost-spirit:x64-windows boost-spirit:x86-windows
- cmd: vcpkg install boost-uuid:x64-windows boost-uuid:x86-windows
- cmd: vcpkg install boost-locale:x64-windows boost-locale:x86-windows
- cmd: vcpkg install boost-iostreams:x64-windows boost-iostreams:x86-windows
- cmd: vcpkg install range-v3:x64-windows range-v3:x86-windows
- cmd: vcpkg integrate install
cache: c:\tools\vcpkg\installed\
build:
  project: CppCoverage.sln
  parallel: true
  verbosity: normal
